### ISSUE TITLE
KeyError: 'Rich Presence'

### ISSUE THREAD

**Issue by dexeonify** [Yolodude25/virtualbox-rich-presence#3]
When I try to launch the script, it returns with the following error:
```
Traceback (most recent call last):
  File "D:\Documents\Others\Virtualbox Rich Presence\presence.py", line 192, in <module>
    rich_presence()
  File "D:\Documents\Others\Virtualbox Rich Presence\presence.py", line 41, in __init__
    client_id = self.config["Rich Presence"]["client_id"]
  File "C:\Users\Blob\AppData\Local\Programs\Python\Python39\lib\configparser.py", line 960, in __getitem__
    raise KeyError(key)
KeyError: 'Rich Presence'
```
- OS: Windows Version 20H2 (Build 19042.685)
- Python: Python 3.9.1 downloaded from [here](https://www.python.org/downloads/)
- All pip packages has been updated.
- `config.ini` has not been modified.

**Comment by vidhanio** [comment]
This is likely because you did not rename the file from
`config.ini.example` to `config.ini`.

**Comment by dexeonify** [comment]
Cool, that was such a simple fix. I swear the last time I used this script I don't have to rename it, but anyways thanks for the help!
