### ISSUE TITLE
presence.py throws errors when starting it

### ISSUE THREAD

**Issue by Saraistupid** [Yolodude25/virtualbox-rich-presence#8]
I've installed the Virtualbox SDK from arch linux repos, installed python-virtualbox too and reinstalled virtualbox and I'm getting an error about XPCOM

```
❯ python presence.py
Traceback (most recent call last):
  File "/home/e404nnf/virtualbox-rich-presence/presence.py", line 192, in <module>
    rich_presence()
  File "/home/e404nnf/virtualbox-rich-presence/presence.py", line 35, in __init__
    self.vbox = virtualbox.VirtualBox()
  File "/home/e404nnf/.local/lib/python3.9/site-packages/virtualbox/library_ext/vbox.py", line 22, in __init__
    manager = virtualbox.Manager()
  File "/home/e404nnf/.local/lib/python3.9/site-packages/virtualbox/__init__.py", line 163, in __init__
    self.manager = vboxapi.VirtualBoxManager(mtype, mparams)
  File "/usr/lib/python3.9/site-packages/vboxapi/__init__.py", line 989, in __init__
    self.platform = PlatformXPCOM(dPlatformParams)
  File "/usr/lib/python3.9/site-packages/vboxapi/__init__.py", line 752, in __init__
    import xpcom.components
  File "/usr/lib/virtualbox/sdk/bindings/xpcom/python/xpcom/components.py", line 240, in <module>
    _shutdownObserver = xpcom.server.WrapObject(_ShutdownObserver(), interfaces.nsIObserver)
  File "/usr/lib/virtualbox/sdk/bindings/xpcom/python/xpcom/server/__init__.py", line 64, in WrapObject
    return _xpcom.WrapObject(policy( ob, iid ), iid, bWrapClient)
  File "/usr/lib/virtualbox/sdk/bindings/xpcom/python/xpcom/server/policy.py", line 161, in __init__
    raise ServerException(nsError.NS_ERROR_NO_INTERFACE)
xpcom.ServerException: 0x80004002 (NS_ERROR_NO_INTERFACE)
```

**Comment by vidhanio** [comment]
Hey! sorry for the wait, just a bit of inactivity.

Searching around, I found this issue: https://github.com/sethmlarson/virtualbox-python/issues/157

can you try the fix there and see if it works? thanks!

**Comment by Saraistupid** [comment]
> Hey! sorry for the wait, just a bit of inactivity.
> 
> Searching around, I found this issue: [sethmlarson/virtualbox-python#157](https://github.com/sethmlarson/virtualbox-python/issues/157)
> 
> can you try the fix there and see if it works? thanks!

Yeah that works, I found out about it recently but forgot to mention it, thanks either way

**Comment by E404NNF** [comment]
> Hey! sorry for the wait, just a bit of inactivity.
> 
> Searching around, I found this issue: [sethmlarson/virtualbox-python#157](https://github.com/sethmlarson/virtualbox-python/issues/157)
> 
> can you try the fix there and see if it works? thanks!

Yeah that works, I found out about it recently but forgot to mention it, thanks either way

**Comment by vidhanio** [comment]
no worries! :)
